# Generated by Django 4.1 on 2025-12-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLModel',
            fields=[
                ('id', models.BigAutoField(help_text='主键ID，自增', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('algorithm', models.CharField(help_text='算法名称（如DQN、PPO等）', max_length=100, verbose_name='算法名称')),
                ('target_episode', models.PositiveIntegerField(help_text='目标训练回合数', verbose_name='目标训练回合数')),
                ('current_episode', models.PositiveIntegerField(default=0, help_text='当前训练回合数', verbose_name='当前训练回合数')),
                ('status', models.SmallIntegerField(choices=[(0, '训练中'), (1, '训练完成')], default=0, help_text='训练状态：0-训练中，1-训练完成', verbose_name='训练状态')),
                ('task_size_average', models.DecimalField(blank=True, decimal_places=4, help_text='任务平均大小', max_digits=10, null=True, verbose_name='任务平均大小')),
                ('task_comsumption_average', models.DecimalField(blank=True, decimal_places=4, help_text='任务平均消耗', max_digits=10, null=True, verbose_name='任务平均消耗')),
                ('task_time_average', models.DecimalField(blank=True, decimal_places=4, help_text='任务平均耗时', max_digits=10, null=True, verbose_name='任务平均耗时')),
                ('task_arrival_rate', models.DecimalField(blank=True, decimal_places=4, help_text='任务到达率', max_digits=8, null=True, verbose_name='任务到达率')),
                ('n_UE', models.PositiveIntegerField(blank=True, help_text='用户设备(UE)数量', null=True, verbose_name='用户设备(UE)数量')),
                ('UE_computation_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='UE计算能力', max_digits=10, null=True, verbose_name='UE计算能力')),
                ('MEC_computation_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='MEC服务器计算能力', max_digits=12, null=True, verbose_name='MEC服务器计算能力')),
                ('seed', models.PositiveIntegerField(blank=True, help_text='随机种子', null=True, verbose_name='随机种子')),
                ('learning_rate', models.DecimalField(blank=True, decimal_places=6, help_text='学习率', max_digits=8, null=True, verbose_name='学习率')),
                ('batch_size', models.PositiveIntegerField(blank=True, help_text='批次大小', null=True, verbose_name='批次大小')),
                ('buffer_size', models.PositiveBigIntegerField(blank=True, help_text='经验回放缓冲区大小', null=True, verbose_name='经验回放缓冲区大小')),
                ('gamma', models.DecimalField(blank=True, decimal_places=6, help_text='折扣因子γ', max_digits=8, null=True, verbose_name='折扣因子γ')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '强化学习模型参数',
                'verbose_name_plural': '强化学习模型参数',
                'db_table': 'rl_model',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.BigAutoField(help_text='主键ID，自增', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('episode', models.PositiveIntegerField(help_text='训练回合数', verbose_name='训练回合数')),
                ('reward', models.DecimalField(blank=True, decimal_places=4, help_text='当前回合奖励值', max_digits=10, null=True, verbose_name='当前回合奖励值')),
                ('smoothed_reward', models.DecimalField(blank=True, decimal_places=4, help_text='平滑奖励值（如滑动平均）', max_digits=10, null=True, verbose_name='平滑奖励值')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('model', models.ForeignKey(help_text='关联的RL模型', on_delete=django.db.models.deletion.CASCADE, to='web.rlmodel', verbose_name='关联模型')),
            ],
            options={
                'verbose_name': '训练数据',
                'verbose_name_plural': '训练数据',
                'db_table': 'train_data',
                'ordering': ['model', 'episode'],
            },
        ),
        migrations.AddIndex(
            model_name='traindata',
            index=models.Index(fields=['model'], name='idx_model_id'),
        ),
    ]
